version: '3.4'

services:
  imagemagick:
    image: davekobrenski/imagemagick-node:arm64-0.1.6
    restart: always
    environment:
      NODE_ENV: production
      SERVICE_URL: ${SERVICE_URL}
      PORT: ${PORT}
      CACHE_DIR: ${CACHE_DIR}
      ENABLE_AUTH: ${ENABLE_AUTH}
      AUTH_IDENTIFIER: ${AUTH_IDENTIFIER}
      AUTH_BASE_URL: ${AUTH_BASE_URL}
    ports:
      - ${PORT}:5100
    volumes:
      - ./public:/im/app/public